### ISSUE TITLE
Double running the application

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#41]
Steps:

1. Put your smartphone to sleep.
2. Wake up the smartphone.
3. Launch the application.

The application starts twice despite tapping the icon once.
This happens until we choose a function from the application, e.g. Settings.

Apps:
Android 10
Package Manager v5.1

**Comment by sunilpaulmathew** [comment]
That is really really strange. May I ask you to show me a screen record to get more idea? Thanks.

**Comment by Valdnet** [comment]
> May I ask you to show me a screen record to get more idea?

I sent the recording to you by email 😉.

**Comment by sunilpaulmathew** [comment]
> rding to you by

Okay, thanks for the message, I found your email which is ended up in my spam folder :)
The issue seems to related with app themes. I guess your phone is in Light Mode, but the app theme is set as Dark? I also noticed that one time UI refreshing when the app theme is different to that of system theme. You can check it by setting system wide dark them (in phone) or auto dark/light mode (in app). I'll look for a permanent solution soon. Btw, thanks for sending me the video.

**Comment by Valdnet** [comment]
> You can check it by setting system wide dark them (in phone) or auto dark / light mode (in app)

After setting a light theme in the application (used in the system) it now starts correctly 😉.

**Comment by sunilpaulmathew** [comment]
@Valdnet I hope this issue also fixed in v5.2. So, closing this issue as well.
