### ISSUE TITLE
Sharing App Issues

### ISSUE THREAD

**Issue by HonestAbe7** [SmartPack/PackageManager#62]
Clicking "More" inside an app then clicking to share it only sends an HTML file. How do I send the app itself? Thanks

**Comment by sunilpaulmathew** [comment]
> Clicking "More" inside an app then clicking to share it only sends an HTML file. How do I send the app itself? Thanks

That is the intended action. We can't directly send APKs (due to permission related issues), without exporting them to a place where app has access (we can, but it will make issues for bigger APKs).

**Solution**: Click on the "Export" icon right down to "More". You'll see a "Share" option once the exporting is completed.

**Comment by HonestAbe7** [comment]
Thank you for explaining this to me! 👍
